### PR TITLE
Switching to docker deploys for Wercker

### PR DESCRIPTION
**Pull request by blisteringherb**
Removing unnecessary code from wercker.yml and updating the build box to support new-world Docker deploys on Wercker.  

https://app.wercker.com/dosomething/northstar-mobilecommonsd/runs

### CODE REVIEW

**Review by DFurnes — APPROVED** [review]
Woooo! ⛵️💨

I noticed the Wercker build didn't get attached to the commit (it's just the two StyleCI hooks), so I tried hitting the "Fix Webhook" button in Wercker... we'll see if that does anything!

Obvs not a blocker since the build succeeded, but just a heads up in case you have any ideas. 😄

**Comment by blisteringherb** [comment]
@DFurnes It looks like that webhook is attached now. I'm not sure if Wercker has changed something where the checks don't get run anymore during a PR, but the push and pull_request should still trigger the builds.

**Comment by DFurnes** [comment]
@blisteringherb Did you mean to merge this PR?

**Comment by blisteringherb** [comment]
@DFurnes Whoops! Clicked the wrong button. Thanks!

**Pull request merged**
