### PR TITLE
Adding Capistrano deploy code.

### PR DESCRIPTION
**Pull request by sheyd**
@DFurnes Thoughts, comments?

### CODE REVIEW

**Comment by DFurnes** [comment]
Do we need a [Capfile](https://github.com/DoSomething/northstar/blob/dev/Capfile) or [Gemfile](https://github.com/DoSomething/northstar/blob/dev/Gemfile)? Our other repositories with Capistrano deploys seem to have them.

**Comment by sheyd** [comment]
💭  Checking!

**Comment by sheyd** [comment]
Added the Capfile and Gemfile, as it is probably required. 🌚

**Comment by DFurnes** [comment]
⛵

**Pull request merged**
